"""add research audit events

Revision ID: 149c348078a1
Revises: 559a375395ae
Create Date: 2026-10-05 15:14:20.912256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '149c348078a1'
down_revision: Union[str, Sequence[str], None] = '559a375395ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('research_run_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('evidence_hash', sa.String(length=64), nullable=True),
    sa.Column('candidate_email', sa.String(length=320), nullable=True),
    sa.Column('candidate_name', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_audit_events_event_type'), 'research_audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_research_audit_events_research_run_id'), 'research_audit_events', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_research_audit_events_source_type'), 'research_audit_events', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_audit_events_source_type'), table_name='research_audit_events')
    op.drop_index(op.f('ix_research_audit_events_research_run_id'), table_name='research_audit_events')
    op.drop_index(op.f('ix_research_audit_events_event_type'), table_name='research_audit_events')
    op.drop_table('research_audit_events')
    # ### end Alembic commands ###
