"""Add email workflow persistence

Revision ID: 1886aaaff2ba
Revises: 239d96eef03a
Create Date: 2026-09-21 08:00:27.147329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1886aaaff2ba'
down_revision: Union[str, Sequence[str], None] = '239d96eef03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_workflows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('email_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('workflow_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('message_id', sa.Text(), nullable=True),
    sa.Column('thread_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['email_account_id'], ['email_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_workflows_email_account_id'), 'email_workflows', ['email_account_id'], unique=False)
    op.create_index(op.f('ix_email_workflows_message_id'), 'email_workflows', ['message_id'], unique=False)
    op.create_index(op.f('ix_email_workflows_provider'), 'email_workflows', ['provider'], unique=False)
    op.create_index(op.f('ix_email_workflows_status'), 'email_workflows', ['status'], unique=False)
    op.create_index(op.f('ix_email_workflows_thread_id'), 'email_workflows', ['thread_id'], unique=False)
    op.create_index(op.f('ix_email_workflows_user_id'), 'email_workflows', ['user_id'], unique=False)
    op.create_index(op.f('ix_email_workflows_workflow_id'), 'email_workflows', ['workflow_id'], unique=True)
    op.create_index(op.f('ix_email_workflows_workflow_type'), 'email_workflows', ['workflow_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_workflows_workflow_type'), table_name='email_workflows')
    op.drop_index(op.f('ix_email_workflows_workflow_id'), table_name='email_workflows')
    op.drop_index(op.f('ix_email_workflows_user_id'), table_name='email_workflows')
    op.drop_index(op.f('ix_email_workflows_thread_id'), table_name='email_workflows')
    op.drop_index(op.f('ix_email_workflows_status'), table_name='email_workflows')
    op.drop_index(op.f('ix_email_workflows_provider'), table_name='email_workflows')
    op.drop_index(op.f('ix_email_workflows_message_id'), table_name='email_workflows')
    op.drop_index(op.f('ix_email_workflows_email_account_id'), table_name='email_workflows')
    op.drop_table('email_workflows')
    # ### end Alembic commands ###
