"""add email recipient uniqueness constraint

Revision ID: 1e0f10286c63
Revises: 69716cde0bc9
Create Date: 2026-09-26 21:48:06.364262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e0f10286c63'
down_revision: Union[str, Sequence[str], None] = '69716cde0bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_email_recipient_message_type_email', 'email_recipients', ['message_id', 'recipient_type', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_email_recipient_message_type_email', 'email_recipients', type_='unique')
    # ### end Alembic commands ###
