"""add research runs

Revision ID: 559a375395ae
Revises: 978ed6ddafca
Create Date: 2026-10-05 04:14:37.072456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559a375395ae'
down_revision: Union[str, Sequence[str], None] = '978ed6ddafca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('research_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['email_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_account_id'), 'research_runs', ['account_id'], unique=False)
    op.create_index(op.f('ix_research_runs_research_type'), 'research_runs', ['research_type'], unique=False)
    op.create_index(op.f('ix_research_runs_run_id'), 'research_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_research_runs_status'), 'research_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_runs_status'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_run_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_research_type'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_account_id'), table_name='research_runs')
    op.drop_table('research_runs')
    # ### end Alembic commands ###
