"""add email message soft delete

Revision ID: 978ed6ddafca
Revises: 1e0f10286c63
Create Date: 2026-09-28 23:50:23.035218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '978ed6ddafca'
down_revision: Union[str, Sequence[str], None] = '1e0f10286c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'email_messages',
        sa.Column(
            'is_deleted',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column(
        'email_messages',
        'is_deleted',
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_messages', 'is_deleted')
    # ### end Alembic commands ###
